paths:
  /recipes:
    get:
      responses:
        200:
          description: OK
      tags:
        - recipes   
    post:
      summary: Adds a new recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
            example:
                  name: Isaac
                  resume: prueba undostres
        description: Data for creating a new recipe
      responses:
        200:
          description: Successfully created a new recipe
        500:
          description: An error occurred while processing the request
      tags:
        - recipes

                