components:
  #-------------------------------
  # Reusable schemas (data models)
  #-------------------------------
  schemas:
    Recipe:    
      type: object
      properties: 
        _id:  
          type: string
        name:  
          type: string
        resume:  
          type: string
        rate:  
          type: number
        healthy_level:
          type: number
        instructions:
          type: string
        img:
          type: string